# Install the following tools for language servers and
# formatters to work:
# mise use -g npm:typescript
# mise use -g npm:typescript-language-server
# mise use -g npm:graphql-language-service-cli
# mise use -g npm:prettier
# brew install ruff
# mise use -g npm:pyright
# brew install clojure-lsp/brew/clojure-lsp-native

[[language]]
name = "javascript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }

[[language]]
name = "graphql"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "graphql"] }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
